CREATE DATABASE IF NOT EXISTS BD_ESTOQUE;
USE BD_ESTOQUE;

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    TIPO VARCHAR(100) NOT NULL
    
);

CREATE TABLE IF NOT EXISTS PRODUTO(
	CODIGO_BARRAS INT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    PRECO DOUBLE NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    DATA_VALIDADE DATE NOT NULL,
    PESO DOUBLE,
    FK_CATEGORIA_ID INT,
    FOREIGN KEY (FK_CATEGORIA_ID) REFERENCES CATEGORIA(ID)
    
);

CREATE TABLE IF NOT EXISTS FORNECEDOR(
	CPF_CNPJ VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255)NOT NULL,
    TELEFONE VARCHAR (9) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTO_FORNECEDOR(
	ID INT PRIMARY KEY,
    FK_PRODUTO_ID INT ,
    FK_FORNECEDOR_CPF_CNPJ VARCHAR NOT NULL,
    FOREIGN KEY (FK_PRODUTO_ID) REFERENCES PRODUTO(ID),
    FOREIGN KEY (FK_FORNECEDOR_CPF_CNPJ) REFERENCES FORNECEDOR(CPF_CNPJ)
);