CREATE DATABASE IF NOT EXISTS BD_MUSICA;
USE BD_MUSICA;

CREATE TABLE IF NOT EXISTS ARTISTA(
	CPF VARCHAR(11) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(9) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ALBUM(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DURACAO TIMESTAMP(6) NOT NULL,
    FK_ARTISTA_CPF VARCHAR(11),
    FOREIGN KEY(FK_ARTISTA_CPF) REFERENCES ARTISTA(CPF)
);

CREATE TABLE IF NOT EXISTS GENERO(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    ESTILO VARCHAR(100) NOT NULL,
    RITMO VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS FAIXA(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    OUVIENTES INT NOT NULL,
    DURACAO TIMESTAMP(6) NOT NULL,
   LETRA VARCHAR(255) NOT NULL,
   NOME VARCHAR(255) NOT NULL,
   FK_GENERO_ID INT,
   FK_ALBUM_ID INT,
   FOREIGN KEY(FK_GENERO_ID) REFERENCES GENERO(ID),
   FOREIGN KEY (FK_ALBUM_ID) REFERENCES ALBUM(ID)
);
